service: graphql-dynamodb

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    HEROES_TABLE: Heroes
    SKILLS_TABLE: Skill
    LOCALSTACK_HOST: ${env:LOCALSTACK_HOST, "localhost"}
    DYNAMODB_PORT: ${env:DYNAMODB_PORT, "4569"}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:DescribeTable
      Resource:  
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.HEROES_TABLE}"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.SKILLS_TABLE}"
package:
  excludeDevDependencies: true
  individually: true

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    stages:
      - ${self:provider.stage}
    start:
      host: ${self:provider.environment.LOCALSTACK_HOST}
      port: ${self:provider.environment.DYNAMODB_PORT}
      migrate: true
      noStart: true
      seed: true
    seed:
      heroes:
        sources:
          - table: ${self:provider.environment.HEROES_TABLE}
            sources: [ './seed/heroes.json' ]
      skills:
        sources:
          - table: ${self:provider.environment.SKILLS_TABLE}
            sources: [ './seed/skills.json' ]

functions:
  graphql:
    handler: handler.handler
    events:
      - http:
          path: graphql
          method: any

resources:
  Resources:
    Heroes:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.HEROES_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    Skills:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.SKILLS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

